//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopWatches.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopWatch
    {
        public int Id { get; set; }
        public bool Active { get; set; }
        public System.DateTime LastTimeUpdated { get; set; }
    }
}
